### ISSUE TITLE
Requesting data or publication inquiries 

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/egret#11]
@lizzieinvancouver @FrederikBaumgarten

Here is a template for us to use when sending out inquires for additional data or looking for publications: 

"My colleagues and I are working on a project looking at the relationship between cold stratification and seed germination. We are currently looking for datasets of seed germination trials for temperate woody species, particularly studies that include data on germination percent, germination rates, or similar responses across different treatments.

I came across the 2001 Ministry of Forests Seed Handling Guidebook, in which is mentions that a number of publications on testing tree seed viability are available from you.

Are you able to suggest any seed germination databases or publications that would include data on germination cues and rates? Or if not, is there anyone I could reach out to who might know of these resources?"

Let me know if you think there is anything to add. I am going to begin by emailing the BC Tree Seed Centre's Seed Improvement officer.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Looks good to me.

Here's what Matt Ayres wrote me:

> Have you explored here? National Seed Laboratory.
> 
> https://www.fs.usda.gov/nsl/
> 
> See if you can find a person to talk to there. Must you seek might be out there if you can find it. Western Europe must have equivalents, and perhaps equivalently hard to pull up
> 
> There is so much knowledge, but diffuse. In my youth, when I was a masters student doing research in Finland, I got to know Matti Sulkinoja, a technician at the field station who every year did large and careful germination studies of mountain birch seeds from the last year. He had been following the same protocol for a few decades when I was there, and he probably succeeded someone else. His target was simply "% germination".  I guess there have been legions of Matti Sulkinojas around the world studying germination for various reasons.
> 
> Also check Davey Institute. Dan Herms is VP of research there.
> 
> Good luck!

**Comment by lizzieinvancouver** [comment]
The only email I could find (bloth@fs.fed.us) for NSL bounced so I called and left a voicemail. I have not reach out to Davey yet, but could.

**Comment by lizzieinvancouver** [comment]
@dbuona @DeirdreLoughnan @FrederikBaumgarten 

I actually got a call back from the USDA's Director of the National Seed Lab (sorry, my phone did not mention his voicemail).. and chatted with him today. Not any data, but good contact. I include my notes below. I am not posting the txt file I have (VicVankus_DirNationalSeedLabUSDA_2024Jan12.txt) since it has email address etc. but here's the rest of it:

<><><><><><>
Overview -- their group basically works on stuff that is sold (so when he says 'native' I think perhaps he doesn't mean 'native/exotic' I think he means a little more 'native/domesticated-horticultural-forestry spp') 

Things to look up probably:
AOSA rules (cost $$) but then I googled and got: https://analyzeseeds.com/wp-content/uploads/2018/03/2017-AOSA-Rules-Volume-3.pdf
International association seed rules (costs $$); googled, got: https://www.idseed.org/pages/seed_testing_rules.html and see https://www.seedtest.org/en/publications/international-rules-seed-testing.html (which is massive website I gave up on quickly)

<><><>
My notes (written on paper and transcribed the same morning that I talked to him):

- Other manuals like the woody plant seed manual? Not many. There is a Chinese one (in Chinese) that he looks at sometimes with tables etc.. He said 'no idea' on European one, but then sounded like perhaps there are some, but not as good as Woody Plant USDA one or Chinese one.

- 'Access to any data is an impossible ask.'

- So you (Lizzie) probably looked at 1996 manual, what is in there is mostly what was in 1974 version, which was pulled mostly from ... 1948 version... and then all those data are gone. 
- Maybe they pushed boxes of data from room to room decade to decade, maybe some got scanned, but mostly thrown out. 
- The book has good data, but some may be from 3 collections of seed total.

- Now, they never try to get optimum germination. 
- They want to know if they can germinate whatever seed using some of the standard testing (see below when I asked for more info on this) ... so 20C or 15/2-C or other standard testing conditions that all labs have.

- For example, recently he a colleague started working on wire grass again (from southeast US) and they know that long ago they did cold Strat and such tests, but they plan to do it all over again now, as they know they don't have the data.

- They are a service lab, not a research lab.

- What is the standard?
	- Standard is AOSA (American Assoc of Seed Analysis) rules
	- There are official germination rules (for groups like ag, turf, forestry trees etc.) where they list what to do.
	- Especially with any standard for native species, the better info is older stuff and no one knows where that info came from.

- He mentioned state seed laws (fascinating!).

- Mostly they test in-house for conservation/preservation agencies/companies ... they do what those groups ask (they pay USDA seed lab to do testing).

- They do cold start etc. but it rarely makes it into rules because usually they find a standard rule (without cold Strat) that works just as well.

- Federal Seed Act -- if you market seed/ag then you need a minimum seed germination % and this is basically for all horticultural etc. seeds so all seed dormancy is bred out.

- One example: one seed company in the US markets yellow poplar, they sell the same lot in 3 conditions:
	(1) they just collect it in the wild and do nothing, still winged etc. -- that germinates at maybe 3%
	(2) they de-wing it and do a little something -- that germinates at maybe 40%
	(3) they do a lot of seed conditioning -- that germinates at 90%
- They sell all these at three totally different prices. Some folks doing a big spread of seeds to sell bare-root seedlings want the 3%, some folks doing other stuff (did not manage to write that down) was the 90%.

- He remembers back when the 1996 Woody Plant Seed manual was put together (he worked on it). And he hopes maybe they will update it someday. If they do, they'll contact 'current, living' seed folks and ask them if the [assigned genus] chapter needs updating. They should probably add some genera or species... next one likely to be online-only... if they get around to it.
- He said we're free to scrape the Woody Plant Seed manual -- he would like the data if we scape it (seemed to think AOSA rules etc. are $$ based). 

- I asked for any European or other contacts and he said he would ask folks and be in touch if he found anyone. He said he is older so most of his contacts are now longer working at Kew etc..

**Comment by lizzieinvancouver** [comment]
I also am trying to track down this [person](https://www.kew.org/science/our-science/people/sarah-adams)

**Comment by lizzieinvancouver** [comment]
I never tracked down Sarah Adams, but I did chat with Carol Baskin in March 2024 when visiting UK Lexington and she suggested the big seed banks may not keep studious data and may spend most of their time trying to check crop seeds are still viable ... so not the data we desperately want. 

Closing this, see notes/otherSourcesSearchDec2023.md
